[pytest]

addopts = -s -rfs

markers =
    inventory_page
    ui_validation

    add_to_cart
    product_clear
    remove_from_cart
    cancel_buy
    product_page_buy
    go_to_home

    login_test
    product_test

    regression
    sanity
    smoke

    functional_e2e
